[tool.poetry]
name = "healthy-habit"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.packages]
-name = "habit"
 from = "."

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"
djangorestframework = "^3.15.2"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.10"
black = "^24.10.0"
djangorestframework-simplejwt = "^5.4.0"
django-filter = "^24.3"
drf-yasg = "^1.21.8"
requests = "^2.32.3"
celery = "^5.4.0"
django-celery-beat = "^2.7.0"
coverage = "^7.6.10"
redis = "^5.2.1"
gevent = "^24.11.1"
pybloom-live = "^4.0.0"
django-cors-headers = "^4.6.0"
gunicorn = "^23.0.0"
django-redis = "^5.4.0"
isort = "^6.0.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
