# Generated by Django 5.1.4 on 2025-01-11 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit",
                    models.CharField(
                        help_text="Укажите название привычки.",
                        max_length=250,
                        verbose_name="Название привычки.",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнять привычку.",
                        max_length=250,
                        null=True,
                        verbose_name="Место, в котором необходимо выполнять привычку.",
                    ),
                ),
                (
                    "time_habit",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку.",
                        null=True,
                        verbose_name="Время, когда необходимо выполнять привычку.",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите действие, которое представляет собой привычка.",
                        max_length=250,
                        null=True,
                        verbose_name="Действие, которое представляет собой привычка.",
                    ),
                ),
                (
                    "pleasant_habit",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите привычку, которую можно привязать к выполнению полезной привычки.",
                        null=True,
                        verbose_name="Привычка, которую можно привязать к выполнению полезной привычки.",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        help_text="Укажите периодичность выполнения привычки для напоминания в днях.",
                        null=True,
                        verbose_name="Периодичность выполнения привычки для напоминания в днях.",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите чем Вы себя вознаградите после выполнения привычки.",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение.",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=120),
                        help_text="Укажите время, которое предположительно Вы потратите на выполнение привычки.",
                        null=True,
                        verbose_name="Время, которое предположительно Вы потратите на выполнение привычки.",
                    ),
                ),
                (
                    "publicity",
                    models.CharField(
                        choices=[
                            ("Опубликована", "Опубликована"),
                            ("Не опубликована", "Не опубликована"),
                        ],
                        default="Не опубликована",
                        help_text="Укажите хотите ли Вы, чтобы другие пользователи видели Ваши привычки.",
                        max_length=20,
                        verbose_name="Статус опубликования привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
